#!/bin/bash
# Cody Brown 
# percentinc bash script
# Sun Jan 14 20:07:42 CST 2018
# *********************************************************
# perceninc(a, b) = (b-a) / a * 100.0
# *********************************************************
val1="$1"
val2="$2"
str1="percent increase = "

result="scale=8;($val2 - $val1) / $val1 * 100.0"  
echo -n "$str1"; echo "$result" | bc -q; 





